package com.sportsfactory.sportforall.dao;

import java.util.ArrayList;

import com.sportsfactory.sportforall.dto.AccountDto;
import com.sportsfactory.sportforall.dto.AlbumLikeDto;
import com.sportsfactory.sportforall.dto.AlbumReplyDto;
import com.sportsfactory.sportforall.dto.AlbumZzimDto;
import com.sportsfactory.sportforall.dto.BoardZzimDto;
import com.sportsfactory.sportforall.dto.ClubBoardDto;
import com.sportsfactory.sportforall.dto.ClubDto;
import com.sportsfactory.sportforall.dto.ClubFeeDto;
import com.sportsfactory.sportforall.dto.ClubInquiryDto;
import com.sportsfactory.sportforall.dto.ClubInviteDto;
import com.sportsfactory.sportforall.dto.ClubPointDto;
import com.sportsfactory.sportforall.dto.ClubSearchLogDto;
import com.sportsfactory.sportforall.dto.ClubUserAddressDto;
import com.sportsfactory.sportforall.dto.LocationDto;
import com.sportsfactory.sportforall.dto.ClubAlbumDto;
import com.sportsfactory.sportforall.dto.ClubUserDto;
import com.sportsfactory.sportforall.dto.ClubUserFeeAddressDto;
import com.sportsfactory.sportforall.dto.ClubUserFeeDto;
import com.sportsfactory.sportforall.dto.ClubUserPaidAddressDto;
import com.sportsfactory.sportforall.dto.ClubUserPaidDto;
import com.sportsfactory.sportforall.dto.CommentDto;
import com.sportsfactory.sportforall.dto.FedManagerDto;
import com.sportsfactory.sportforall.dto.SportsTypeDto;
import com.sportsfactory.sportforall.dto.JsonDto;
import com.sportsfactory.sportforall.dto.LikeDto;

public interface ClubDao {
	/**
	 * 
	 * @param dto
	 * @return
	 */
	public ArrayList<ClubDto> getClubList(ClubDto dto);
	public ArrayList<ClubDto> getCategoryClubList(ClubDto dto);
	public ArrayList<ClubDto> getFedList(ClubDto dto);
	public ClubAlbumDto getCreatedClubAlbum(ClubAlbumDto dto);
	public ArrayList<ClubBoardDto> getClubNotice(ClubBoardDto dto);
	public ArrayList<ClubBoardDto> getClubBoard(ClubBoardDto dto);
	public ArrayList<ClubBoardDto> getClubBoardRestricted(ClubBoardDto dto);
	public void insertClubBoard(ClubBoardDto dto);
	public void updateClubBoard(ClubBoardDto dto);
	public void deleteClubBoard(ClubBoardDto dto);
	public void insertCommentBoard(CommentDto dto);
	public ClubDto getClubInfo(ClubDto dto);
	public ClubUserDto getClubLevel(ClubUserDto dto);
	public void insertClubAlbum(ClubAlbumDto dto);
	public JsonDto getCountLike(ClubBoardDto dto);
	public JsonDto getCountComment(ClubBoardDto dto);
	public void insertClubPicture(ClubAlbumDto dto);
	public ArrayList<ClubAlbumDto> getAllClubAlbum(ClubAlbumDto dto);
	public ClubBoardDto getClubBoardView(ClubBoardDto dto);
	public ArrayList<CommentDto> getMainComment(ClubBoardDto dto);
	public ArrayList<CommentDto> getReplyComment(CommentDto dto);
	public ArrayList<LikeDto> getLike(ClubBoardDto dto);
	public int ifLike(ClubBoardDto dto);
	public void updateClubTitle(ClubAlbumDto dto);
	public ClubAlbumDto getClubAlbum(ClubAlbumDto dto);
	public ArrayList<ClubAlbumDto> getClubAlbumView(ClubAlbumDto dto);
	public void likeThis(ClubBoardDto dto);
	public void dislikeThis(ClubBoardDto dto);
	public void insertAlbumReply(AlbumReplyDto dto);
	public ArrayList<AlbumReplyDto> getAllAlbumReply(AlbumReplyDto dto);
	public AlbumReplyDto getAlbumReply(AlbumReplyDto dto);
	public void likeAlbum(AlbumLikeDto dto);
	public AlbumLikeDto getAlbumLike(AlbumLikeDto dto);
	public void dislikeAlbum(AlbumLikeDto dto);
	public void albumDelete(ClubAlbumDto dto);
	public void albumUpdate(ClubAlbumDto dto);
	public ArrayList<ClubUserDto> getClubUser(ClubUserDto dto);
	public void zzimAlbum(AlbumZzimDto dto);
	public AlbumZzimDto getAlbumZzim(AlbumZzimDto dto);
	public void ZzimCancel(AlbumZzimDto dto);
	public int ifBoardZzim(BoardZzimDto zdto);
	public void zzimThis(BoardZzimDto zdto);
	public void diszzimThis(BoardZzimDto zdto);
	public void insertClubInquiry(ClubInquiryDto dto);
	public void updateClubInquiry(ClubInquiryDto dto);
	public ArrayList<ClubAlbumDto> getAlbumSearch(ClubAlbumDto dto);
	public ArrayList<ClubAlbumDto> getAlbumMore(ClubAlbumDto dto);
	public ArrayList<ClubAlbumDto> getAlbumSearchMore(ClubAlbumDto dto);
	public ArrayList<ClubInquiryDto> getClubInquiry(ClubInquiryDto cdto);
	public ClubInquiryDto getClubInquiryView(ClubInquiryDto cdto);
	public int ifResponsed(ClubInquiryDto cdto);
	public ArrayList<ClubUserPaidDto> getClubUserPaid(ClubUserPaidDto dto);
	public void userPaidCheck(ClubUserPaidDto dto);
	public void userPaidUncheck(ClubUserPaidDto dto);
	public ArrayList<ClubDto> getAllClubType();
	public ArrayList<ClubDto> getAllClubTarget();
	public void makeClub(ClubDto dto);
	public void insertClubUser(ClubUserDto cUdto);
	public void insertUserFee(ClubUserFeeDto dto);
	public ArrayList<ClubUserFeeDto> getClubUserFee(ClubUserFeeDto dto);
	public void deleteFeeList(ClubUserFeeDto dto);
	public void updateClubInfoMainPic(ClubDto dto);
	public void updateClubInfoClubName(ClubDto dto);
	public void updateClubInfoSkillPoint(ClubDto dto);
	public void updateClubInfoMatchDate(ClubDto dto);
	public void updateClubInfoExercisePlace(ClubDto dto);
	public void updateClubInfoExerciseTime(ClubDto dto);
	public void updateClubInfoClubTargetCode(ClubDto dto);
	public void updateClubInfoIntroduction(ClubDto dto);
	public void insertClubFee(ClubFeeDto dto);
	public ArrayList<ClubUserDto> getManagers(ClubUserDto dto);
	public int isAgreedDeleteClub(ClubUserDto dto);
	public void agreeDeleteClub(ClubUserDto dto);
	public int countNotAgreedDeleteClub(ClubUserDto dto);
	public void confirmDeleteClub(ClubDto dto);
	public void inviteUser(ClubInviteDto dto);
	public ArrayList<ClubInviteDto> getSameInvite(ClubInviteDto dto);
	public void incrementStackInvite(ClubInviteDto dto);
	public void insertAddressUser(ClubUserAddressDto dto);
	public ClubFeeDto getClubFee(ClubFeeDto dto);
	public ArrayList<ClubUserFeeAddressDto> getClubUserAddressFee(ClubUserFeeAddressDto dto);
	public ClubUserAddressDto getAddressUser(ClubUserAddressDto dto);
	public void insertAddressUserFee(ClubUserFeeAddressDto dto);
	public void deleteAddressFeeList(ClubUserFeeAddressDto dto);
	public int isClubMember(ClubUserDto dto);
	public void setInviteState(ClubInviteDto dto);
	public ArrayList<ClubSearchLogDto> getClubSearchLog(ClubSearchLogDto dto);
	public void insertLogSearch(ClubSearchLogDto dto);
	public ArrayList<ClubDto> getClubSearchResult(ClubDto dto);
	public ArrayList<ClubPointDto> getPointPolicy();
	public int getCountClubUserForPoints(ClubPointDto pPdto);
	public int getCountClubBoardForPoints(ClubPointDto pPdto);
	public int getCountClubAlbumForPoints(ClubPointDto pPdto);
	public int getCountClubInquiryResponseForPoints(ClubPointDto pPdto);
	public void deleteUserAddress(ClubUserAddressDto dto);
	public ArrayList<ClubUserPaidAddressDto> getClubUserAddressPaid(ClubUserPaidAddressDto dto);
	public void insertUserPaidAddress(ClubUserPaidAddressDto dto);
	public void deleteUserPaidAddress(ClubUserPaidAddressDto dto);
	public AlbumReplyDto getAlbumReplyById(AlbumReplyDto dto);
	public void updateAlbumReply(AlbumReplyDto dto);
	public void deleteAlbumReply(AlbumReplyDto dto);
	public ClubPointDto getUserPoint(ClubDto cdto);
	public ClubPointDto getBoardPoint(ClubDto cdto);
	public ClubPointDto getAlbumPoint(ClubDto cdto);
	public ClubPointDto getInquiryPoint(ClubDto cdto);
	public int isClubZzimed(ClubDto cdto);
	public void zzimClub(ClubDto cdto);
	public void diszzimClub(ClubDto cdto);
	public ArrayList<ClubDto> getClubListForUser(ClubDto cdto);
	public void updateMainPic(ClubDto dto);
	public ClubDto getFedInfo(ClubDto cdto);
	public ArrayList<ClubDto> getFedMember(ClubDto cdto);
	public void updateFedInquiry(ClubInquiryDto cIdto);
	public void insertFedInquiry(ClubInquiryDto cIdto);
	public String getClubUserNumber(ClubDto dto);
	public void setClubUserLevel(ClubUserDto cUdto);
	public void dropFedMember(ClubDto cdto);
	public void insertFedManager(ClubUserDto cUdto);
	public ArrayList<ClubDto> getClubSearchForFed(ClubDto cdto);
	public void insertFedMember(ClubDto cdto);
	public ArrayList<AccountDto> getUserSearchForFed(AccountDto adto);
	public ArrayList<ClubUserDto> getFedManager(ClubUserDto cUdto);
	public void dropFedManager(ClubUserDto cUdto);
	public ArrayList<ClubInquiryDto> getFedInquiry(ClubInquiryDto cIdto);
	public ClubInquiryDto getFedInquiryView(ClubInquiryDto cIdto);
	public int ifResponsedFed(ClubInquiryDto cIdto);
	public ClubBoardDto getFedBoardView(ClubBoardDto cBdto);
	public ClubUserDto getFedUserLevel(ClubUserDto cUdto);
	public ArrayList<ClubBoardDto> getFedNotice(ClubBoardDto cBdto);
	public ArrayList<ClubBoardDto> getFedBoard(ClubBoardDto cBdto);
	public JsonDto getCountLikeFed(ClubBoardDto cBdto);
	public JsonDto getCountCommentFed(ClubBoardDto cBdto);
	public int getFedBoardIsZzimed(BoardZzimDto bZdto);
	public int getFedBoardIsLiked(LikeDto ldto);
	public int getFedBoardCountLike(LikeDto ldto);
	public ArrayList<CommentDto> getMainCommentFed(ClubBoardDto cBdto);
	public ArrayList<CommentDto> getReplyCommentFed(CommentDto cdto);
	public void zzimFedBoard(BoardZzimDto bZdto);
	public void diszzimFedBoard(BoardZzimDto bZdto);
	public void likeFedBoard(LikeDto ldto);
	public void dislikeFedBoard(LikeDto ldto);
	public void modifyComment(CommentDto cdto);
	public void modifyFedComment(CommentDto cdto);
	public void deleteComment(CommentDto cdto);
	public void deleteFedComment(CommentDto cdto);
	public void insertCommentBoardFed(CommentDto cdto);
	public void insertFedBoard(ClubBoardDto cBdto);
	public void updateFedBoard(ClubBoardDto cBdto);
	public void deleteFedBoard(ClubBoardDto cBdto);
	public ArrayList<ClubDto> getFedMemberNotJoined(ClubDto cdto);
	public ClubDto getFedClubCode(ClubDto dto);
	public ClubDto getClubRank(ClubDto pdto);
	public ClubDto isOverlapClubName(ClubDto cdto);
	public void default_main_picture(ClubDto dto);
	public void dropClubManager(ClubUserDto dto);
	public ClubDto getClubRankCategory(ClubDto cdto);
	public FedManagerDto getFedManagerLevel(FedManagerDto dto);
	public int getCountClubManager(ClubUserDto cUdto);
	public void updateClubInfoMemberNum(ClubDto cdto);
}